// <auto-generated />
using System;
using MVCShoppingFinal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCShoppingFinal.Migrations
{
    [DbContext(typeof(ShopDatabaseContext))]
    [Migration("20201111233626_MVCShoppingFinal.Context.ShopDatabaseContextTryFinal")]
    partial class MVCShoppingFinalContextShopDatabaseContextTryFinal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCShopping.Models.Negocio", b =>
                {
                    b.Property<int>("idNegocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idNegocio");

                    b.ToTable("infoNegocio");
                });

            modelBuilder.Entity("MVCShopping.Models.Producto", b =>
                {
                    b.Property<int>("idProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaProd")
                        .HasColumnType("int");

                    b.Property<int>("ColorProd")
                        .HasColumnType("int");

                    b.Property<int>("CurrentNegocioId")
                        .HasColumnType("int");

                    b.Property<int?>("NegocioidNegocio")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("precio")
                        .HasColumnType("real");

                    b.Property<int>("talle")
                        .HasColumnType("int");

                    b.HasKey("idProducto");

                    b.HasIndex("NegocioidNegocio");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("MVCShopping.Models.Producto", b =>
                {
                    b.HasOne("MVCShopping.Models.Negocio", "Negocio")
                        .WithMany("Productos")
                        .HasForeignKey("NegocioidNegocio");
                });
#pragma warning restore 612, 618
        }
    }
}
