// <auto-generated />
using MVCShoppingFinal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCShoppingFinal.Migrations
{
    [DbContext(typeof(ShopDatabaseContext))]
    [Migration("20201108201646_MVCShoppingFinal.Context.ShopDatabaseContextIntento2iCollection")]
    partial class MVCShoppingFinalContextShopDatabaseContextIntento2iCollection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCShopping.Models.Negocio", b =>
                {
                    b.Property<int>("idNegocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idNegocio");

                    b.ToTable("infoNegocio");
                });
#pragma warning restore 612, 618
        }
    }
}
